
name: Compile Release Notes

on:
  workflow_call:
    inputs:
      icloudpd_version:
        required: true
        type: string

jobs:

  build_notes:
    runs-on: ubuntu-24.04
    steps:

    - name: Download artifacts (compatibility)
      uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5
      with:
        name: icloudpd-compatibility
        path: |
          dist

    - name: Download artifacts (changelog)
      uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5
      with:
        name: icloudpd-changelog
        path: |
          dist

    - name: Merge Release Notes
      run: |
        cat dist/changelog-*.md > dist/notes-${{inputs.icloudpd_version}}.md
        cat dist/compatibility-*.md >> dist/notes-${{inputs.icloudpd_version}}.md

    - name: Upload artifacts
      uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5
      with:
        name: icloudpd-notes
        if-no-files-found: error
        path: |
          dist/notes-${{inputs.icloudpd_version}}.md
